//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;
namespace EatryOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodItem()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int FoodId { get; set; }

        [DisplayName("Item")]

        public string FoodName { get; set; }
        public int CategoryId { get; set; }
        public Nullable<decimal> Price { get; set; }

        [DisplayName("Special Dish")]
        public string IsSpecial { get; set; }
        [DisplayName("Image")]
        public string imagepath { get; set; }




        public HttpPostedFileBase ImageFile { get; set; }

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
